# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('cover_image', models.ImageField(upload_to=b'')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=8)),
                ('discount', models.PositiveIntegerField(db_index=True, default=0)),
                ('qty_in_stock', models.PositiveIntegerField(db_index=True, default=0)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[['english', '\u0410\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438\u0439'], ['russian', '\u0420\u0443\u0441\u0441\u043a\u0438\u0439']], db_index=True, max_length=32)),
                ('published_date', models.DateField(db_index=True)),
                ('num_of_pages', models.IntegerField()),
                ('isbn', models.PositiveIntegerField(db_index=True)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('authors', models.ManyToManyField(related_name='books', to='z_store.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[['experience_level', '\u0423\u0440\u043e\u0432\u0435\u043d\u044c \u043f\u043e\u0434\u0433\u043e\u0442\u043e\u0432\u043a\u0438'], ['programming_language', '\u042f\u0437\u044b\u043a \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f']], db_index=True, max_length=32)),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('address', models.TextField()),
                ('comment_by_customer', models.TextField(blank=True)),
                ('comment_by_store', models.TextField(blank=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_time', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=8)),
                ('book_discount', models.PositiveIntegerField(db_index=True, default=0)),
                ('book_qty', models.PositiveIntegerField(db_index=True, default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_store.Book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_store.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[['placed', '\u0417\u0430\u043a\u0430\u0437 \u0441\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d'], ['confirmed', '\u0417\u0430\u043a\u0430\u0437 \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d'], ['shipped', '\u0417\u0430\u043a\u0430\u0437 \u043e\u0442\u0433\u0440\u0443\u0436\u0435\u043d'], ['delivered', '\u0417\u0430\u043a\u0430\u0437 \u0434\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d'], ['canceled_by_customer', '\u0417\u0430\u043a\u0430\u0437 \u043e\u0442\u043c\u0435\u043d\u0435\u043d \u041a\u043b\u0438\u0435\u043d\u0442\u043e\u043c'], ['canceled_by_store', '\u0417\u0430\u043a\u0430\u0437 \u043e\u0442\u043c\u0435\u043d\u0435\u043d \u041c\u0430\u0433\u0430\u0437\u0438\u043d\u043e\u043c']], db_index=True, max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_time', models.DateTimeField(auto_now=True, db_index=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='z_store.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]], db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z_store.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(through='z_store.OrderBook', to='z_store.Book'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='z_store.Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='publishers',
            field=models.ManyToManyField(related_name='books', to='z_store.Publisher'),
        ),
        migrations.AlterUniqueTogether(
            name='orderstatus',
            unique_together=set([('order', 'status')]),
        ),
    ]
