# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='book_discount',
        ),
    ]
