# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('z_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderstatus',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '\u0410\u0432\u0442\u043e\u0440', 'verbose_name_plural': '\u0410\u0432\u0442\u043e\u0440\u044b'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '\u041a\u043d\u0438\u0433\u0430', 'verbose_name_plural': '\u041a\u043d\u0438\u0433\u0438'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f', 'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '\u0417\u0430\u043a\u0430\u0437', 'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b'},
        ),
        migrations.AlterModelOptions(
            name='orderbook',
            options={'verbose_name': '\u0417\u0430\u043a\u0430\u0437\u0430\u043d\u043d\u0430\u044f \u043a\u043d\u0438\u0433\u0430', 'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u0430\u043d\u043d\u044b\u0435 \u043a\u043d\u0438\u0433\u0438'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': '\u0418\u0437\u0434\u0430\u0442\u0435\u043b\u044c', 'verbose_name_plural': '\u0418\u0437\u0434\u0430\u0442\u0435\u043b\u0438'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '\u041e\u0431\u0437\u043e\u0440', 'verbose_name_plural': '\u041e\u0431\u0437\u043e\u0440\u044b'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='updated_time',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='archive',
            field=models.BooleanField(db_index=True, default=False, verbose_name='\u0410\u0440\u0445\u0438\u0432?'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[['initiated', '\u0417\u0430\u043a\u0430\u0437 \u0438\u043d\u0438\u0446\u0438\u0438\u0440\u043e\u0432\u0430\u043d \u041a\u043b\u0438\u0435\u043d\u0442\u043e\u043c'], ['placed', '\u0417\u0430\u043a\u0430\u0437 \u0440\u0430\u0437\u043c\u0435\u0449\u0435\u043d \u041a\u043b\u0438\u0435\u043d\u0442\u043e\u043c'], ['confirmed', '\u0417\u0430\u043a\u0430\u0437 \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d \u041c\u0430\u0433\u0430\u0437\u0438\u043d\u043e\u043c'], ['delivered', '\u0417\u0430\u043a\u0430\u0437 \u0434\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d \u041c\u0430\u0433\u0430\u0437\u0438\u043d\u043e\u043c'], ['canceled_by_customer', '\u0417\u0430\u043a\u0430\u0437 \u043e\u0442\u043c\u0435\u043d\u0435\u043d \u041a\u043b\u0438\u0435\u043d\u0442\u043e\u043c'], ['canceled_by_store', '\u0417\u0430\u043a\u0430\u0437 \u043e\u0442\u043c\u0435\u043d\u0435\u043d \u041c\u0430\u0433\u0430\u0437\u0438\u043d\u043e\u043c']], db_index=True, default=['initiated', '\u0417\u0430\u043a\u0430\u0437 \u0438\u043d\u0438\u0446\u0438\u0438\u0440\u043e\u0432\u0430\u043d \u041a\u043b\u0438\u0435\u043d\u0442\u043e\u043c'], max_length=32, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='z_store.Author', verbose_name='\u0410\u0432\u0442\u043e\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='z_store.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to=b'', verbose_name='\u041e\u0431\u043b\u043e\u0436\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='book',
            name='discount',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 %'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.PositiveIntegerField(db_index=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[['english', '\u0410\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438\u0439'], ['russian', '\u0420\u0443\u0441\u0441\u043a\u0438\u0439']], db_index=True, max_length=32, verbose_name='\u042f\u0437\u044b\u043a'),
        ),
        migrations.AlterField(
            model_name='book',
            name='num_of_pages',
            field=models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0441\u0442\u0440\u0430\u043d\u0438\u0446'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=8, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(db_index=True, verbose_name='\u0414\u0430\u0442\u0430 \u0432\u044b\u0445\u043e\u0434\u0430'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishers',
            field=models.ManyToManyField(related_name='books', to='z_store.Publisher', verbose_name='\u0418\u0437\u0434\u0430\u0442\u0435\u043b\u0438'),
        ),
        migrations.AlterField(
            model_name='book',
            name='qty_in_stock',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432 \u043d\u0430\u043b\u0438\u0447\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='\u0410\u0434\u0440\u0435\u0441 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(through='z_store.OrderBook', to='z_store.Book', verbose_name='\u041a\u043d\u0438\u0433\u0438 \u0432 \u0437\u0430\u043a\u0430\u0437\u0435'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment_by_customer',
            field=models.TextField(blank=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u041a\u043b\u0438\u0435\u043d\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment_by_store',
            field=models.TextField(blank=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u041c\u0430\u0433\u0430\u0437\u0438\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(db_index=True, max_length=32, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0439 \u0442\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u043b\u0438\u0435\u043d\u0442'),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='book_discount',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 %'),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='book_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=8, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='book_qty',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='z_store.Book', verbose_name='\u041a\u043d\u0438\u0433\u0430'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]], db_index=True, verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433 \u043a\u043d\u0438\u0433\u0438'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e\u0431\u0437\u043e\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u043b\u0438\u0435\u043d\u0442'),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
