# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('z_store', '0002_auto_20160209_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publishers',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='z_store.Publisher', verbose_name='\u0418\u0437\u0434\u0430\u0442\u0435\u043b\u044c'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='\u0424\u0418\u041e'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[['en', '\u0410\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438\u0439'], ['ru', '\u0420\u0443\u0441\u0441\u043a\u0438\u0439']], db_index=True, max_length=2, verbose_name='\u042f\u0437\u044b\u043a'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='\u041d\u0430\u0437\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
